kingphisher:
  build: .
  hostname: kingphisher
  links:
  - postgres
  ports: 
  - "80:80"
  - "22:22"
postgres:
  image: dshimola/kingpsql
  hostname: postgres
  volumes_from:
  - postgresdata
postgresdata:
  image: dshimola/kingpsql
  entrypoint: /bin/true
  
